" 语法高亮
syntax on
set backspace=2

"自动对齐
set autoindent

"显示输入的命令
set showcmd

"显示行号
set nu

"系统快捷键
set clipboard=unnamed

"突出显示当前行
"set cursorline

"启动显示状态行
set laststatus=1

"编码设置
set encoding=utf-8

"鼠标可用
set mouse=a

"tab缩进
set tabstop=4       "一个 tab 显示出来是多少个空格，默认 8
set shiftwidth=4    "每一级缩进是多少个空格
set expandtab
set smarttab

"显示标尺，就是在右下角显示光标位置
set ruler

"显示匹配
set showmatch

"文件自动检测外部更改
set autoread

"c文件自动缩进
set cindent

" 指定屏幕上可以进行分割布局的区域
set splitbelow               " 允许在下部分割布局
set splitright               " 允许在右侧分隔布局

set nocompatible	         " Use Vim defaults instead of vi compatibility
filetype off                 " required

filetype plugin indent on  "required


"设置 vim-plug!!!
call plug#begin('$HOME/vimfiles/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jiangmiao/auto-pairs'

call plug#end()

"light airline主题
"let g:airline_theme='deus'
let g:airline_theme='bubblegum'
